#pragma once


#define MAX_ENTITIES 1024

#define SCREEN_WIDTH_IN_PIXELS  640
#define SCREEN_HEIGHT_IN_PIXELS 640

#define SCREEN_WIDTH_METERS  4
#define SCREEN_HEIGHT_METERS 4

#define OBJECT_RADIUS 0.01
